const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('frontend/assets/js/autobot.js','utf8');
const start = source.indexOf('    function safeFramePath');
const end = source.indexOf('    function refreshIcons');
const changes=[], storage=new Map();
const ctx={URL,currentFramePath:'', window:{location:{href:'https://crm.example/app/autobot'},history:{state:{route:'autobot'},replaceState(state,unused,path){changes.push({state,path});}},sessionStorage:{setItem(k,v){storage.set(k,v);}}}};
vm.createContext(ctx);vm.runInContext(source.slice(start,end),ctx);
const origin='https://crm.example';
const route='/tenders/0171200001926000664?tab=files#suppliers';
assert.equal(ctx.safeFramePath(route,origin),route);
assert.equal(ctx.safeFramePath('/autobot'+route,origin),'/autobot'+route);
for(const bad of ['//evil.example/tenders','https://evil.example/tenders','/api/tenders/12345678/delete','/app/users','/tenders/../../api/auth/me','/tenders/12345678#<script>'])assert.equal(ctx.safeFramePath(bad,origin),'');
assert.equal(ctx.safeFramePath('/estimates?_pmbi_reload=3',origin),'/estimates');
assert.equal(ctx.safeFramePath('/autobot/api/tenders/12345678/delete',origin),'');
ctx.rememberFramePath(route,origin);
assert.equal(ctx.currentFramePath,route);
assert.equal(new URL(changes[0].path,origin).searchParams.get('autobot'),route);
assert.equal(changes[0].state.route,'autobot');
assert.equal(storage.get('pmbi-autobot-location:'+origin),route);
console.log('autobot_location_frontend_ok');
