const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (name) => fs.readFileSync(path.join(root, name), 'utf8');
const coreJs = read('frontend/assets/js/core.js');
const appJs = read('frontend/assets/js/app.js');
const planningJs = read('frontend/assets/js/planning.js');
const warehouseControlJs = read('frontend/assets/js/warehouse-control.js');
const objectControlCss = read('frontend/assets/css/object-control.css');
const warehousePy = read('backend/warehouse.py');
const dailyTasksHtml = read('frontend/pages/daily_tasks.html');

const sidebarStart = coreJs.indexOf('function bindSidebarControls()');
const sidebarEnd = coreJs.indexOf('bindSidebarControls();', sidebarStart);
const sidebarBlock = coreJs.slice(sidebarStart, sidebarEnd);
assert.match(sidebarBlock, /document\.addEventListener\('click'/);
assert.match(sidebarBlock, /event\.target\.closest\('\[data-menu-toggle\]'\)/);
assert.match(sidebarBlock, /document\.body\.classList\.toggle\('menu-open'\)/);
assert.doesNotMatch(sidebarBlock, /toggle\.addEventListener\('click'/);

assert.match(coreJs, /projectsLoaded: false/);
assert.match(appJs, /state\.projectsLoaded = true/);
const reminderStart = appJs.indexOf('function refreshReminderBell()');
const reminderEnd = appJs.indexOf('function initReminderBell()', reminderStart);
const reminderBlock = appJs.slice(reminderStart, reminderEnd);
assert.match(reminderBlock, /if \(!state\.projectsLoaded\)/);
assert.match(reminderBlock, /if \(!state\.projects\.length\) \{\s*renderReminderBell\(\[\], false\);\s*return;/);

assert.match(appJs, /loadProjectAssignments = function \(projectId, loadingToken\) \{\s*loadProjectHub\(projectId, state\.selectedProject, loadingToken\);/);
assert.match(warehousePy, /^import urllib\.parse$/m);
assert.match(planningJs, /errorCode === 'works_required'\s*\? 'Сначала загрузите смету с работами\.'/);
assert.match(dailyTasksHtml, /<h1>Задачи сотрудников<\/h1>/);
assert.match(dailyTasksHtml, /Назначайте задачи, следите за выполнением/);
assert.match(warehouseControlJs, /warehouse-material-register-head/);
assert.match(warehouseControlJs, /<span>Нужно по смете<\/span><span>Куплено<\/span><span>Привезено<\/span><span>Потрачено<\/span><span>Остаток<\/span>/);
assert.match(warehouseControlJs, /data-warehouse-dialog-open="movement"/);
assert.match(warehouseControlJs, /data-warehouse-dialog-open="work-fact"/);
assert.match(warehouseControlJs, /data-warehouse-dialog-open="norms"/);
assert.match(warehouseControlJs, /data-warehouse-dialog-open="history"/);
assert.match(warehouseControlJs, /'<div class="warehouse-control-main">' \+ materialsTable\(payload\) \+ '<\/div>'/);
assert.match(warehouseControlJs, /data-warehouse-control-portal/);
assert.match(warehouseControlJs, /document\.body\.appendChild\(portal\)/);
assert.match(warehouseControlJs, /document\.addEventListener\('keydown', dialogKeydownHandler\)/);
assert.match(warehouseControlJs, /aria-label="Поиск материалов"/);
assert.match(warehouseControlJs, /data-warehouse-stock-filter="all" aria-pressed="true"/);
assert.match(warehouseControlJs, /data-select-material-button/);
assert.doesNotMatch(warehouseControlJs, /warehouse-material-card is-' \+ stateLabel\[2\] \+ '"' \+ \(payload\.canRecordFacts \? ' tabindex="0" role="button"'/);
assert.match(planningJs, /section-work-register-head/);
assert.match(planningJs, /<span>Работа<\/span><span>Объём<\/span><span>Статус<\/span>/);
assert.match(planningJs, /section-work-register-master-head/);
assert.match(planningJs, /section-work-register-section/);
assert.match(planningJs, /section-work-section-volume/);
assert.match(planningJs, /section-work-section-status/);
assert.match(planningJs, /section-work-section-meta/);
assert.equal((planningJs.match(/section-work-register-head/g) || []).length, 1);
const workSectionStart = planningJs.indexOf('function renderSectionScheduleRow');
const workSectionEnd = planningJs.indexOf('function renderSectionScheduleForecast', workSectionStart);
const workSectionBlock = planningJs.slice(workSectionStart, workSectionEnd);
assert.doesNotMatch(workSectionBlock, /renderWorkProgressStrip/);
assert.doesNotMatch(workSectionBlock, /data-section-schedule-toggle|section-schedule-chevron|renderScheduleSectionDetailsShell/);
assert.match(workSectionBlock, /section-work-register-body/);
assert.match(planningJs, /works-register-summary/);
assert.match(planningJs, /works-register-summary-item is-period/);
assert.match(planningJs, /<span><\/span><span>Работа<\/span><span>Объём<\/span><span>Статус<\/span><\/div>/);
assert.match(objectControlCss, /\.warehouse-material-card \{[\s\S]*?border: 0;[\s\S]*?border-bottom: 1px solid/);
assert.match(objectControlCss, /\.section-work-check\.schedule-work-duration-row \{[\s\S]*?border: 0 !important;/);
assert.match(objectControlCss, /\.warehouse-control-main \{[\s\S]*?display: block;/);
assert.match(objectControlCss, /\.warehouse-control-dialog \{[\s\S]*?position: fixed;/);
assert.match(objectControlCss, /\.project-schedule-view-switcher\.market-toolbar \{[\s\S]*?background: transparent !important;/);
assert.match(objectControlCss, /\.section-schedule-caption \{[\s\S]*?display: none !important;/);
assert.match(objectControlCss, /\.warehouse-control-workspace \{[\s\S]*?padding: 6px 8px 24px;/);
assert.match(objectControlCss, /\.section-work-section-row \{[\s\S]*?grid-template-columns:/);
assert.match(objectControlCss, /\.section-work-register-master-head \{[\s\S]*?background: var\(--color-surface-subtle\);/);
assert.match(objectControlCss, /\[data-project-overview-section\]\[hidden\] \{\s*display: none !important;/);
assert.match(objectControlCss, /\.warehouse-control-head \{[\s\S]*?flex-direction: column;/);
assert.match(objectControlCss, /\.warehouse-control-head-actions \{[\s\S]*?grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
assert.match(objectControlCss, /\.warehouse-material-card \{[\s\S]*?grid-template-columns: repeat\(3, minmax\(0, 1fr\)\);/);
assert.match(objectControlCss, /\.warehouse-control-dialog-card \{[\s\S]*?max-height: min\(820px, calc\(100dvh - 48px\)\);/);
assert.match(appJs, /aria-label="Отметить весь раздел выполненным"/);
assert.match(objectControlCss, /Compact works register/);
assert.match(objectControlCss, /\.section-work-section-row \{[\s\S]*?min-height: 50px;[\s\S]*?padding: 7px 12px;/);
assert.match(objectControlCss, /\.section-work-register-section \.section-work-check\.schedule-work-duration-row \{[\s\S]*?min-height: 44px !important;/);
assert.match(objectControlCss, /\.project-estimate-file-copy > span \{\s*display: none;/);
assert.match(objectControlCss, /Works table foundation/);
assert.match(objectControlCss, /\.section-work-register-body[\s\S]*?display: block;/);
assert.match(objectControlCss, /Works register controls and summary/);
assert.match(objectControlCss, /\.works-register-summary \{[\s\S]*?grid-template-columns: minmax\(230px, 1\.6fr\) repeat\(3, minmax\(110px, \.6fr\)\);/);
assert.match(objectControlCss, /input\[type="checkbox"\]\[data-section-work-check\][\s\S]*?width: 20px !important;[\s\S]*?height: 20px !important;/);
assert.match(objectControlCss, /data-section-work-check\]\):checked,[\s\S]*?background: var\(--color-accent\) !important;/);
assert.match(objectControlCss, /input\[type="checkbox"\]\[data-section-work-check\][\s\S]*?border-radius: 4px;/);

console.log('browser_regression_frontend_ok');
