const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (name) => fs.readFileSync(path.join(root, name), 'utf8');
const appJs = read('frontend/assets/js/app.js');
const planningJs = read('frontend/assets/js/planning.js');
const routerJs = read('frontend/assets/js/router.js');
const baseHtml = read('frontend/templates/base.html');

const bulkStart = appJs.indexOf('function normalizeBulkSectionKind');
const bulkEnd = appJs.indexOf('function saveActualQuantityInput', bulkStart);
const bulkBlock = appJs.slice(bulkStart, bulkEnd);

assert.ok(bulkStart >= 0 && bulkEnd > bulkStart);
assert.match(bulkBlock, /value === 'work' \|\| value === 'works'/);
assert.match(bulkBlock, /value === 'material' \|\| value === 'materials'/);
assert.match(bulkBlock, /itemKind: normalizeBulkSectionKind\(itemKind\)/);
assert.match(bulkBlock, /function sectionBulkInputs\(scope, itemKind\)/);
assert.match(bulkBlock, /normalizedKind === 'work'[\s\S]*?'\[data-section-work-check\]'/);
assert.match(bulkBlock, /normalizedKind === 'material'[\s\S]*?'\[data-section-material-check\]'/);
assert.match(bulkBlock, /sectionBulkInputs\(scope, bulk \? bulk\.getAttribute\('data-bulk-kind'\) : ''\)/);
assert.match(bulkBlock, /function bulkSectionItemIds\(scope, itemKind\)[\s\S]*?sectionBulkInputs\(scope, itemKind\)/);
assert.match(bulkBlock, /function completeBulkSectionLocally\(scope, checked, itemKind\)[\s\S]*?sectionBulkInputs\(scope, normalizedKind\)/);
assert.match(bulkBlock, /setScheduleWorkDone\(projectId, sectionTitle/);
assert.match(bulkBlock, /setMaterialManuallyDone\(projectId, materialItem, checked\)/);
assert.match(bulkBlock, /updateMaterialScheduleItemDom\(materialItem\.id, checked\)/);
assert.match(bulkBlock, /var actualKind = normalizeBulkSectionKind\(input\.getAttribute\('data-actual-kind'\)\);\s*return !normalizedKind \|\| actualKind === normalizedKind;/);
assert.match(bulkBlock, /var bulkKind = normalizeBulkSectionKind\(input\.getAttribute\('data-bulk-kind'\)\)/);
assert.match(bulkBlock, /var itemIds = bulkSectionItemIds\(scope, bulkKind\)/);
assert.match(bulkBlock, /completeBulkSectionLocally\(scope, checked, bulkKind\);\s*input\.indeterminate = false;\s*updateBulkSectionCheckState\(scope\)/);
assert.match(bulkBlock, /bulkCompleteSectionProgress\(projectId, sectionTitle, checked, itemIds, bulkKind\)/);
assert.match(bulkBlock, /input\.checked = !checked;\s*completeBulkSectionLocally\(scope, !checked, bulkKind\);\s*updateBulkSectionCheckState\(scope\)/);
assert.match(appJs, /function workMatchingKeys[\s\S]*?keys\.push\('id\|' \+ String\(item\.id\)\)[\s\S]*?keys\.push\(scheduleWorkKey\(sectionTitle, item\)\)/);
assert.doesNotMatch(appJs, /renderBulkSectionCheckbox\(projectId, title, 'works', workProgress\)/);
assert.match(appJs, /section-work-section-icon[\s\S]*?data-lucide="layers-3"/);
assert.match(appJs, /var itemLabel = itemKind === 'work' \? 'работы' : \(itemKind === 'material' \? 'материалы' : 'позиции'\)/);
assert.match(appJs, /var ariaLabel = 'Отметить все ' \+ itemLabel \+ ' раздела выполненными'/);
assert.match(appJs, /aria-label="' \+ escapeHtml\(ariaLabel\) \+ '" data-bulk-section-check/);
assert.doesNotMatch(planningJs, /renderBulkSectionCheckbox\(project\.id, sectionTitle, 'work', progress\)/);
assert.match(planningJs, /data-work-quantity-open/);
assert.doesNotMatch(planningJs.slice(planningJs.indexOf('function renderSectionScheduleRow'), planningJs.indexOf('function renderSectionScheduleForecast')), /data-section-work-check|data-bulk-section-check/);
assert.match(planningJs, /if \(forcedOpen\) return false;\s*if \(item && \(item\.isCompleted \|\| item\.is_completed\)\) return true/);
assert.match(planningJs, /entry\.isCompleted = !!isDone/);
assert.match(routerJs, /app\.js\?v=[^']*bulk-section-completion-1/);
assert.match(routerJs, /planning\.js\?v=[^']*bulk-section-completion-1/);
assert.match(routerJs, /app\.js\?v=[^']*works-bulk-right-1/);
assert.match(routerJs, /planning\.js\?v=[^']*works-bulk-right-1/);
assert.match(baseHtml, /router\.js\?v=20260903-report-ux-r1/);

console.log('bulk_section_completion_frontend_ok');
