const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (name) => fs.readFileSync(path.join(root, name), 'utf8');
const app = read('frontend/assets/js/app.js');
const planning = read('frontend/assets/js/planning.js');
const operations = read('frontend/assets/js/operations.js');
const warehouse = read('frontend/assets/js/warehouse-control.js');
const router = read('frontend/assets/js/router.js');
const css = read('frontend/assets/css/position-editor.css');
const appCss = read('frontend/assets/app.css');
const base = read('frontend/templates/base.html');
const login = read('frontend/templates/login.html');
const projectsPage = read('frontend/pages/projects.html');
const reconciliation = read('frontend/assets/js/estimate-reconciliation.js');
const server = read('backend/server.py');

assert.match(appCss, /position-editor\.css\?v=20260825-position-editor-1-kind-switch-1-position-duration-1/);
assert.match(base, /app\.css\?v=[^"\s]*position-editor-1/);
assert.match(base, /router\.js\?v=[^"\s]*position-editor-1/);
assert.match(router, /app\.js\?v=[^'\s]*position-editor-1/);
assert.match(base, /app\.css\?v=[^"\s]*kind-switch-1/);
assert.match(base, /router\.js\?v=[^"\s]*kind-switch-1/);
assert.match(router, /app\.js\?v=[^'\s]*kind-switch-1/);
assert.match(router, /planning\.js\?v=[^'\s]*position-editor-1/);
assert.match(router, /warehouse-control\.js\?v=[^'\s]*position-editor-1/);
assert.match(base, /app\.css\?v=[^"\s]*position-duration-1/);
assert.match(base, /router\.js\?v=[^"\s]*position-duration-1/);
assert.match(login, /app\.css\?v=[^"\s]*position-duration-1/);
assert.match(login, /app\.js\?v=[^"\s]*position-duration-1/);
assert.match(router, /app\.js\?v=[^'\s]*position-duration-1/);
assert.match(router, /planning\.js\?v=[^'\s]*position-duration-1/);
assert.match(base, /router\.js\?v=[^"\s]*estimate-repair-1/);
assert.match(router, /app\.js\?v=[^'\s]*estimate-repair-1/);
assert.match(router, /planning\.js\?v=[^'\s]*estimate-repair-1/);
assert.match(router, /estimate-reconciliation\.js\?v=[^'\s]*estimate-repair-1/);
assert.match(router, /operations\.js\?v=[^'\s]*estimate-repair-1/);
assert.match(projectsPage, /data-tab="estimate-reconciliation"[^>]*>[\s\S]*?<span>Сверка импорта<\/span>/);
assert.match(reconciliation, /Это сравнение неизменяемых версий/);
assert.match(reconciliation, /Решения здесь не редактируют рабочие строки сметы и не меняют бюджет/);

const anomalyStart = app.indexOf('} else if (estimateAnomaly) {');
const anomalyEnd = app.indexOf('\n            }', anomalyStart);
const anomaly = app.slice(anomalyStart, anomalyEnd);
assert.ok(anomalyStart >= 0 && anomalyEnd > anomalyStart);
assert.match(anomaly, /Проверьте импортированные объёмы и цены по строкам/);
assert.match(anomaly, /label: 'Разобрать сумму'/);
assert.match(anomaly, /tab: 'schedule'/);
assert.match(anomaly, /scheduleMode: 'table'/);
assert.doesNotMatch(anomaly, /tab: 'estimate-reconciliation'/);
assert.match(app, /data-project-schedule-mode-target=/);
assert.match(operations, /dataset\.projectScheduleModeTarget/);
assert.match(operations, /setProjectTabMode\(selectedProjectId, 'schedule', scheduleMode\)/);
assert.match(operations, /\[data-project-schedule-mode=/);

const editorStart = app.indexOf('function positionEditorItemFromRow');
const editorEnd = app.indexOf('var positionHighlightTimer', editorStart);
const editor = app.slice(editorStart, editorEnd);
assert.ok(editorStart >= 0 && editorEnd > editorStart);
assert.match(editor, /role="dialog" aria-modal="true" aria-labelledby="position-editor-title"/);
assert.match(editor, /data-position-editor-form novalidate/);
assert.match(editor, /name="title"/);
assert.match(editor, /name="section_title"/);
assert.match(editor, /name="unit"/);
assert.match(editor, /name="planned_qty"/);
assert.match(editor, /canViewProcurementPrices\(\) \? '<label[^']*name="planned_price"/);
assert.match(editor, /plannedPrice: source\.planned_price/);
assert.match(editor, /<fieldset class="position-editor-kind"><legend>Тип позиции<\/legend>/);
assert.match(editor, /type="radio" name="position_kind" value="material"/);
assert.match(editor, /type="radio" name="position_kind" value="work"/);
assert.match(editor, /data-position-kind-warning role="status" aria-live="polite"/);
assert.match(editor, /data-position-duration-panel hidden/);
assert.match(editor, /name="schedule_duration_days" type="number" min="0\.5" max="3650" step="0\.5"/);
assert.match(editor, /data-position-duration-step="-0\.5"/);
assert.match(editor, /data-position-duration-step="0\.5"/);
assert.match(editor, /data-position-duration-auto>Авто/);
assert.match(editor, /item\.kind === 'work' && selectedKind === 'work'/);
assert.match(editor, /positionEditorDurationSubmitting/);
assert.match(editor, /\/section-schedule-override/);
assert.match(editor, /\{ item_id: item\.itemId, duration_days: durationDays \}/);
assert.match(editor, /\{ item_id: item\.itemId, reset: true \}/);
assert.match(editor, /document\.addEventListener\('contextmenu'/);
assert.equal((editor.match(/document\.addEventListener\('contextmenu'/g) || []).length, 1);
assert.match(editor, /if \(!row \|\| !canManageSchedule\(\)\) return;\s*event\.preventDefault\(\)/);
assert.match(editor, /event\.key === 'ContextMenu' \|\| \(event\.shiftKey && event\.key === 'F10'\)/);
assert.match(editor, /closest\('\[data-position-editor-open\]'\)/);
assert.match(editor, /openPositionEditor\(row, opener\)/);
assert.match(editor, /positionEditorSubmitting/);
assert.match(editor, /\/api\/projects\/.*\/estimate-items\/.*\/update/);
assert.match(editor, /expectedKind: item\.kind/);
assert.match(editor, /targetKind: selectedKind/);
assert.match(editor, /updatePayload\.plannedPrice = price/);
assert.match(editor, /Number\.isFinite\(price\) \|\| price < 0/);
assert.match(editor, /estimate_position_price_invalid/);
assert.match(editor, /price_fields_forbidden/);
assert.match(editor, /refreshProjectOverview\(item\.projectId\)/);
assert.match(editor, /response && response\.itemKind/);
assert.match(editor, /estimate_position_kind_change_blocked/);
assert.match(editor, /activateProjectTab\('schedule'\)/);
assert.match(editor, /activateProjectTab\('warehouse-control'\)/);
assert.match(editor, /PMBI\.warehouseControl\.load\(projectId, true\)/);
assert.match(editor, /PMBI\.planning\.loadSectionScheduleForecast/);
assert.match(editor, /PMBI\.warehouseControl\.patchPosition/);
assert.doesNotMatch(editor, /openProject\(/);
assert.doesNotMatch(editor, /MutationObserver|setInterval|offsetWidth/);

assert.match(warehouse, /data-position-editor data-position-kind="material"/);
assert.match(warehouse, /data-position-project=/);
assert.match(warehouse, /function patchPosition\(projectId, item\)/);
assert.match(warehouse, /PMBI\.app\.highlightPositionRow\(card\)/);
assert.match(planning, /data-work-row data-position-editor data-position-kind="work"/);
assert.match(planning, /data-position-auto-days=/);
assert.match(planning, /data-position-duration-days=/);
assert.match(planning, /data-position-duration-overridden=/);
assert.match(planning, /sourceItem: item/);
assert.match(planning, /data-position-price=/);
assert.match(planning, /var canEdit = canManageSchedule\(\)/);
assert.match(planning, /data-position-editor-open>Изменить/);
assert.doesNotMatch(planning, /data-graph-duration-/);
assert.match(planning, /schedule-work-duration-row is-stage" data-stage-id=/);
assert.match(planning, /schedule-stage-row" data-stage-id=/);
assert.match(planning, /function focusProjectScheduleTarget\(target, projectId\)/);
assert.match(planning, /\[data-work-row\]\[data-position-id=/);
assert.match(planning, /\[data-stage-id=/);

assert.match(app, /&tab=schedule&stageId=' \+ encodeURIComponent\(stage\.id \|\| ''\)/);
assert.match(app, /function handleReminderNavigation\(sourceUrl\)/);
assert.match(router, /link\.classList\.contains\('reminder-item'\)/);
assert.match(router, /PMBI\.app\.handleReminderNavigation\(url, link\)/);
assert.match(router, /function syncCurrentUrl\(\)/);
assert.match(app, /consumeProjectDeepLink\('material'\)/);
assert.match(app, /consumeProjectDeepLink\(target\.workId \? 'work' : 'stage'\)/);

const initPageStart = app.indexOf('function initPage()');
const initPageEnd = app.indexOf('function loadProjects', initPageStart);
const initPage = app.slice(initPageStart, initPageEnd);
assert.match(initPage, /loadUserDirectory\(function \(\) \{\}\);\s*loadProjects\(function \(\) \{\s*renderProjectsPage\(\);\s*loadDashboard/);
assert.doesNotMatch(initPage, /loadUserDirectory\(function \(\) \{\s*loadProjects/);

assert.match(css, /\.position-target-focus/);
assert.match(css, /box-shadow: inset 3px 0 0 #3b82f6/);
assert.match(css, /\.position-editor-overlay\[hidden\]/);
assert.match(css, /@media \(max-width: 620px\)/);
assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(css, /\.position-editor-kind-switch/);
assert.match(css, /\.position-editor-duration-stepper/);
assert.match(css, /\.position-editor-duration-auto/);
assert.match(css, /\.position-editor-duration\[hidden\]/);
assert.match(css, /input:focus-visible \+ span/);
assert.match(css, /label:first-child input:checked \+ span/);
assert.match(css, /label:last-child input:checked \+ span/);

assert.match(server, /re\.fullmatch\(r"\/api\/projects\/\\d\+\/estimate-items\/\\d\+\/update"/);
assert.match(server, /def api_update_estimate_position\(self, path: str\)/);
assert.match(server, /user_can_manage_schedule\(user\)/);
assert.match(server, /estimate_position_fields_forbidden/);
assert.match(server, /"before": before, "after": after/);
assert.match(server, /item_kind_override/);
assert.match(server, /estimate_position_kind_change_blocked/);
assert.match(server, /change_estimate_position_kind/);
assert.match(server, /WHEN item_kind_override IN \('material','work'\) THEN item_kind_override/);

const estimateSubmitStart = editor.indexOf("api('/api/projects/' + item.projectId + '/estimate-items/'");
const estimateSubmitEnd = editor.indexOf('}).then(function (response)', estimateSubmitStart);
const estimateSubmit = editor.slice(estimateSubmitStart, estimateSubmitEnd);
assert.ok(estimateSubmitStart >= 0 && estimateSubmitEnd > estimateSubmitStart);
assert.doesNotMatch(estimateSubmit, /duration_days|schedule_duration_days|section-schedule-override/);

console.log('position_editor_frontend_ok');
